#!/usr/bin/env bash

for flag in "$FLAG_1" "$FLAG_2" ;do
	case "$flag" in
		-q|--quiet)
			export VERBOSE=0
			;;
		-a|--auto)
			export AUTO_OP_FLATPAKS=1
			;;
		-aq|-qa)
			export VERBOSE=0
			export AUTO_OP_FLATPAKS=1
			;;
	esac
done
silencer_check() {
	if [ "$VERBOSE" -eq 0 ]; then
		"$@" >/dev/null
	else
		"$@"
	fi
}

