#!/usr/bin/env bash

for flag in "$FLAG_1" "$FLAG_2" ;do
	case "$flag" in
		-q|--quiet)
			VERBOSE=0
			;;
		-a|--auto)
			AUTO_OP_FLATPAKS=1
			;;
		-aq|-qa)
			VERBOSE=0
			AUTO_OP_FLATPAKS=1
			;;
	esac
done
silencer_check() {
	if [ "$VERBOSE" -eq 0 ]; then
		$@ >/dev/null
	else
		$@
	fi
}

