#!/usr/bin/env bash

SERVICE_DIR="$HOME/.config/systemd/user/"
INT_REGEX='^[0-9]+$'

# function check-dir_cache
check-dir_cache

# Main flag handling
while (($# > 0)); do
    case "$1" in
    -D | --debug)
        shift
        continue
        ;;
    -v | --version)
        printf "flatsync: ${FLATSYNC_VERSION}v\n"
        exitsh 0
        ;;
    -a | --automatic)
        AUTO_OP_FLATPAKS=true
        VERBOSE=false
        printf "Last run: \n%s" "$(date "%H:%M:%S - %d/%m/%Y")" >"$FLATSYNC_CACHE/running_automaticaly"
        ;;
    -R | --remove-systemd)
        systemctl --user disable --now flatsync.timer >/dev/null 2>&1 || true
        rm -f "$SERVICE_DIR"/flatsync.{timer,service}
        systemctl --user daemon-reload
        exitsh 0
        ;;
    -S | --systemd)
        shift
        int=${1:-10}
        if [[ ! "$int" =~ $INT_REGEX ]]; then
            printf "Error: \"%s\" is an invalid value! \n" "$int"
            printf "Flag '-S'|'--systemd' doesn't support chars or floats.\n"

            printf "SCHEDULE FLAG FAILED DUE TO INVALID VALUE!" &>/dev/null # 1
            exitsh 1
        else
            SCHEDULE_DURATION=$int
            mkdir -p "$HOME"/.config/systemd/user
        fi

        if systemctl --user is-enabled --quiet flatsync.timer; then
            systemctl --user disable --now flatsync.timer >/dev/null 2>&1 || true
            CH_SCHEDULE=true
        else
            CH_SCHEDULE=false
        fi
        cat >"$SERVICE_DIR"/flatsync.service <<EOF
[Unit]
Description=Run FlatSync

[Service]
Type=oneshot
ExecStart=/usr/local/bin/flatsync --automatic
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
EOF
        cat >"$SERVICE_DIR"/flatsync.timer <<EOF
[Unit]
Description=Run FlatSync every ${SCHEDULE_DURATION} minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=${SCHEDULE_DURATION}min
AccuracySec=1s
Persistent=true

[Install]
WantedBy=timers.target
EOF
        systemctl --user daemon-reload
        if [ $CH_SCHEDULE == true ]; then
            systemctl --user enable --now flatsync.timer
        elif [ $CH_SCHEDULE == false ]; then
            systemctl --user reset-failed
            systemctl --user enable flatsync.timer
            systemctl --user restart flatsync.timer
        fi
        printf "FlatSync will run every %s minutes from now on.\n" "$SCHEDULE_DURATION"
        exitsh 0
        ;;
    --id)
        shift
        option=${1:-"get"}
        case "$option" in
        "create")
            if [ "$(whoami)" != root ]; then
                if ! sudo -v; then
                    echo -e "${BRED}Failed to elevate privileges! \n${BYELLOW}Exiting...${NC}\n"
                    exitsh 1
                fi
            fi
            if [ -s "$FLATSYNC_GIT"/last_updated_device ] && [ -s /usr/share/flatsync/flatsync-id ]; then
                OLD_ID_LOCAL=$(printf "%s" "$(cat /usr/share/flatsync/flatsync-id)")
                LAST_ID=$(tail -n 1 "$FLATSYNC_GIT"/last_updated_device)
                if [ "$OLD_ID_LOCAL" == "$LAST_ID" ]; then
                    UPDATE_LUD=true
                fi
            fi
            ###
            printf "%s" "$(openssl rand -base64 32)" | sudo tee /usr/share/flatsync/flatsync-id >/dev/null
            sudo chown root:root /usr/share/flatsync/flatsync-id
            sudo chmod 644 /usr/share/flatsync/flatsync-id
            ###
            UPDATE_LUD=${UPDATE_LUD:-"true"}
            if [ "$UPDATE_LUD" == true ]; then
                cd "$FLATSYNC_GIT"
                LUD_FLATSYNC_ID=$(printf "%s" "$(cat /usr/share/flatsync/flatsync-id)")
                printf "%s\n%s" "$(cat /etc/hostname)" "$LUD_FLATSYNC_ID" 1>last_updated_device
                git add .
                if git commit -q -m "$(date "%H:%M:%S - %d/%m/%Y")" &>/dev/null; then
                    git push -q
                else
                    exitsh 0
                fi
            fi
            ###
            exitsh 0
            ;;
        "get")
            if [ -s /usr/share/flatsync/flatsync-id ]; then
                printf "${BGREEN}The current ID of this device is:${NC}\n%s\n" \
                    "$(cat /usr/share/flatsync/flatsync-id)"
            else
                printf "${BRED}No ID found!!! Run ${BCYAN}flatsync --id=make${BRED} to create it ${NC}\n"
            fi

            exitsh 0
            ;;
        *)
            echo "Error! Flag '--id' requires an option ('create' or 'get')!"

            exitsh 1
            ;;
        esac
        ;;
    -?* | *)
        printf "Error: Unknown flag '%s'\n" "$1"
        exitsh 1
        ;;
    esac
    shift
done

silencer_check() {
    if [ "$VERBOSE" == false ]; then
        "$@" >/dev/null
    else
        "$@"
    fi
}
