#!/usr/bin/env bash

git_preference=(
	"user.name" # id = 0
	"user.email"
	"core.sshCommand"
	"user.signingKey"
	"gpg.format"
)
git_preference_value=(
	"flatsync" # id = 0
	"flatsync@fake.mail"
	"ssh -o IdentitiesOnly=yes -i $FLATSYNC_SSH/flatsync_key"
	"$FLATSYNC_SSH/flatsync_key.pub"
	"ssh"
)
