#!/usr/bin/env bash

FLAG_1="$1" # comment.?
FLAG_2="$2" # comment.?

# start	comment.4 ####
NC='\033[0m' # No Color
BCYAN='\033[1;36m'
BGREEN='\033[1;32m'
BYELLOW='\033[1;33m'
BRED='\033[1;31m'
# end	comment.4 ####

FLATSYNC_SCRIPT="$FLATSYNC_ROOT/scripts"
FLATSYNC_CACHE="$HOME/.cache/flatsync"
FLATSYNC_GIT="$FLATSYNC_DATA/git"
FLATSYNC_SSH="$FLATSYNC_DATA/ssh"

VERBOSE=1 # comment.?
AUTO_OP_FLATPAKS=0 # comment.?
NO_TODO=0 # comment.?

