#!/usr/bin/env bash

FLATSYNC_VERSION="1.10.1"

# comment.4 #############
NC='\033[0m' # No Color
BRED='\033[1;31m'
BGREEN='\033[1;32m'
BYELLOW='\033[1;33m'
BLBLUE='\033[1;34m'
BCYAN='\033[1;36m'
#########################

FLATSYNC_CACHE="$HOME/.cache/flatsync"
FLATSYNC_GIT="$FLATSYNC_DATA/git"
FLATSYNC_SSH="$FLATSYNC_DATA/ssh"

VERBOSE=true           # comment.?
AUTO_OP_FLATPAKS=false # comment.?
NO_TODO=0              # comment.?
