#!/usr/bin/env bash

# start	comment.4 ####
NC='\033[0m' # No Color
BCYAN='\033[1;36m'
BGREEN='\033[1;32m'
BYELLOW='\033[1;33m'
BRED='\033[1;31m'
# end	comment.4 ####
DATE=$(date "%H.%M.%S_%d.%m.%Y") # comment-3.1

FLATSYNC_SCRIPT="$FLATSYNC_ROOT/scripts"
FLATSYNC_CACHE="$HOME/.cache/flatsync"
FLATSYNC_GIT="$FLATSYNC_DATA/git"
FLATSYNC_SSH="$FLATSYNC_DATA/ssh"

NO_TODO=0 # comment.?

