#!/usr/bin/env bash

### Exit on error and failure on unset variables ###
set -euo pipefail
trap 'printf "❌ \033[1;31m\b Error occurred! \033[1;33m\b Exiting...\033[0m\n" && exit 1' ERR
######
source source/global_variables
source source/global_functions

mkdir -p $FLATSYNC_DATA/{git,cache,history}

flatpak list --columns=application --app |
	tee -p "$FLATSYNC_DATA"/local_flatpaks &>/dev/null
cp "$FLATSYNC_DATA"/git/remote_flatpaks "$FLATSYNC_DATA"/cache/

diff "$FLATSYNC_DATA"/remote_flatpaks "$FLATSYNC_DATA"/local_flatpaks |
	grep ">" |
	awk -F ">" '{ print $2 }' |
	tr -d "\n" |
	tee -p "$FLATSYNC_DATA"/uninstall &>/dev/null # comment.2
diff "$FLATSYNC_DATA"/remote_flatpaks "$FLATSYNC_DATA"/local_flatpaks |
	grep "<" |
	awk -F "<" '{ print $2 }' |
	tr -d "\n" |
	tee -p "$FLATSYNC_DATA"/install &>/dev/null # comment.1

echo -e "${BRED}Removing...${NC}"
flatpak uninstall "$(<"$FLATSYNC_DATA"/cache/uninstall)"
echo -e "${BGREEN}Installing...${NC}"
flatpak install "$(<"$FLATSYNC_DATA"/cache/install)"

mv -v remote_flatpaks "$FLATSYNC_DATA"/history/synced_flatpaks-"$DATE".old
shred -u local_flatpaks

flatpak list --columns=application --app |tee -p "$FLATSYNC_DATA"/git/remote_flatpaks &>/dev/null
