#!/usr/bin/env bash

### Exit on error and failure on unset variables ###
set -euo pipefail
trap 'printf "❌ \033[1;31m\b Error occurred! \033[1;33m\b Exiting...\033[0m\n" && exit 1' ERR
### Setting important stuff ###
FLATSYNC_ROOT="$PWD"                # comment.?
FLATSYNC_DATA="$FLATSYNC_ROOT/data" # comment.5
import() {
	local FLATSYNC_IMPORTS="$FLATSYNC_ROOT"/app/import
	local library=$1
	source "$FLATSYNC_IMPORTS"/"$library"
}
#source "$FLATSYNC_SCRIPT"/check-if-FLATSYNC_DATA-dirs-exists.sh
######

import pure_bash_functions
import global_variables
import progress_bar_by_task_completion
import wait_with_spinner_loading

source "$FLATSYNC_SCRIPT"/git.sh

source "$FLATSYNC_SCRIPT"/compare.sh

if [ -e "$FLATSYNC_CACHE"/uninstall ]; then
	echo -e "${BRED}Removing...${NC}"
	source "$FLATSYNC_SCRIPT"/uninstall_apps.sh
else
	echo -e "${BYELLOW}Nothing to remove${NC}"
	$((NO_TODO++))
	printf "$NO_TODO\n"
fi

if [ -e "$FLATSYNC_CACHE"/install ]; then
	echo -e "${BGREEN}Installing...${NC}"
	source "$FLATSYNC_SCRIPT"/install_apps.sh
else
	echo -e "${BYELLOW}Nothing to install${NC}"
	$((NO_TODO++))
	printf "$NO_TODO\n"
fi

source "$FLATSYNC_SCRIPT"/exit.sh

