#!/usr/bin/env bash

# start	comment.4 ####
NC='\033[0m' # No Color
BCYAN='\033[1;36m'
BGREEN='\033[1;32m'
BYELLOW='\033[1;33m'
BRED='\033[1;31m'
# end	comment.4 ####

FLATSYNC_SCRIPT="$FLATSYNC_DATA"/app/source
FLATSYNC_CACHE="$FLATSYNC_DATA"/cache
FLATSYNC_GIT="$FLATSYNC_DATA"/git

