#!/usr/bin/env bash

git_preference=(
	"user.name"
	"user.email"
	"core.sshCommand"
	"user.signingKey"
	"gpg.format"
	"commit.gpgsign"
)
git_preference_value=(
	"'flatsync'"
	"'flatsync@fake.mail'"
	"'ssh -o IdentitiesOnly=yes -i ~/.ssh/flatsync_key'"
	"'~/.ssh/flatsync_key.pub'"
	"ssh"
	"true"
)
