#!/usr/bin/env bash

printf "Processing data...\n"
for appid in $("$FLATSYNC_DATA"/app/cache/uninstall); do
	uninstallid+=("$appid")
done

total="$((${#uninstallid[@]} - 1))"
for index in "${!uninstallid[@]}"; do
	appid=${uninstallid[$index]}
	show_progress "$index" "$total"
	printf "\t\b + $(flatpak search --columns=name $index | tr -d "\n"): " | tee -pa "$FLATSYNC_DATA"/app/cache/uninstall-notice.tmp &> /dev/null
	printf "$(flatpak search --columns=description $index | tr -d "\n")\n" | tee -pa "$FLATSYNC_DATA"/app/cache/uninstall-notice.tmp &> /dev/null
	uninstall2+=("$(flatpak search --columns=name $index | tr -d "\n")")
done

printf "To be uninstalled:\n"
sleep 2s;
cat "$FLATSYNC_DATA"/app/cache/uninstall-notice.tmp
shred -u "$FLATSYNC_DATA"/app/cache/uninstall-notice.tmp
#read -rp "Install? [y/n]: " ASWR
ASWR="y"

if [ $ASWR = y ]; then
	for index in "${!uninstall2[@]}"; do
		set -euo pipefail
		trap 'printf "❌ \033[1;31m\b Error occurred! \033[1;33m\b Exiting...\033[0m\n" && exit 1' ERR

		appid=${uninstallid[$index]}
		app_name=${uninstall2[$index]}

		printf "%s" "$app_name"

		#sleep 2s
		flatpak uninstall --noninteractive "$appid" &> /dev/null 

		printf "%*s[ OK ]\n" $(( 40 - ${#app_name} )) ""
	done
else
	exit 0
fi

